name: Integration and deployment

on:
  push:
    branches:
      - trunk
      - 'maint-**'
  pull_request:
    branches: [ "trunk" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ github.token }}
  ARTIFACTS: packages

jobs:
  ubuntu-integration:

#    if: false

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:

    - name: Project checkout
      uses: actions/checkout@v3
      with:
        # Number of commits to fetch. 0 indicates all history for all branches and tags (default 1).
        fetch-depth: '0'

    - name: Install project pre-requisites
      # install Ninja 'cause of the automatic build parallelism tuned with the
      # number of processors found in the hosting system
      run: |
        sudo apt update
        sudo apt upgrade -y
        sudo apt install -y default-jdk libboost-all-dev lintian ninja-build

    - name: CMake configuration
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -GNinja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DODOX_TESTS=ON

    - name: Build executables
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Performs tests
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Create platform dependent binary packages
      working-directory: ${{github.workspace}}/build
      run: cpack

    - name: Upload produced artifacts
      uses: actions/upload-artifact@v3
      id: upload-artifacts
      with:
        name: ${{env.ARTIFACTS}}
        path: ${{github.workspace}}/build/*.deb

  fedora-integration:

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:

    - name: Project checkout
      uses: actions/checkout@v3
      with:
        # Number of commits to fetch. 0 indicates all history for all branches and tags (default 1).
        fetch-depth: '0'

    - name: Docker build & run
      working-directory: ${{github.workspace}}/docker
      run: |
        mkdir ${{github.workspace}}/build
        docker build -t odox-fedora -f Dockerfile.fedora .
        docker run -t --volume $(realpath ${{github.workspace}}):/in --volume $(realpath ${{github.workspace}})/build:/out odox-fedora /in /out ${{env.BUILD_TYPE}}

    - name: Upload produced artifacts
      uses: actions/upload-artifact@v3
      id: upload-artifacts
      with:
        name: ${{env.ARTIFACTS}}
        path: ${{github.workspace}}/build/*.rpm

  macos-integration:

#    if: false

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:

    - name: Project checkout
      uses: actions/checkout@v3
      with:
        # Number of commits to fetch. 0 indicates all history for all branches and tags (default 1).
        fetch-depth: '0'

    - name: Install project pre-requisites
      # install Ninja 'cause of the automatic build parallelism tuned with the
      # number of processors found in the hosting system
      run: brew install boost ninja

    # antlr-4.12.0-complete.jar is compiled with a bytecode v55.
    # according to [Class File Versions](https://javaalmanac.io/bytecode/versions/)
    # this correspond to a java v11 that we require because the default provided
    # is java 8 (so bytecode v52)
    - name: Install correct Java version
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        check-latest: true

    - name: CMake configuration
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -GNinja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DODOX_TESTS=ON

    - name: Build executables
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Performs tests
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Create platform dependent binary packages
      working-directory: ${{github.workspace}}/build
      run: cpack

    - name: Upload produced artifacts
      uses: actions/upload-artifact@v3
      id: upload-artifacts
      with:
        name: ${{env.ARTIFACTS}}
        path: ${{github.workspace}}/build/*.pkg

  windows-integration:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          base-devel
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-gcc

    # antlr-4.12.0-complete.jar is compiled with a bytecode v55.
    # according to [Class File Versions](https://javaalmanac.io/bytecode/versions/)
    # this correspond to a java v11 that we require because the default provided
    # is java 8 (so bytecode v52)
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        check-latest: true

    - name: Project checkout
      uses: actions/checkout@v3
      with:
        # Number of commits to fetch. 0 indicates all history for all branches and tags (default 1).
        fetch-depth: '0'

    - name: Configure CMake
      run: |
        cmake -GNinja -B '${{github.workspace}}\build' -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DODOX_TESTS=ON -DBOOST_ROOT=D:/a/_temp/msys64/mingw64
        ls -l "${{github.workspace}}\build\share\OrthoDocs"

    - name: Build
      run: cmake --build '${{github.workspace}}\build' --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}\build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        set MSYSTEM=MINGW64
        msys2 -c 'ctest -C ${{env.BUILD_TYPE}} -T test --output-on-failure'

    # creates binary package
    - name: Create package
      working-directory: ${{github.workspace}}\build
      run: cpack

    - name: Upload produced artifacts
      uses: actions/upload-artifact@v3
      id: upload-artifacts
      with:
        name: ${{env.ARTIFACTS}}
        path: ${{github.workspace}}\build\*.exe

  deployment:
    needs: [fedora-integration, macos-integration, ubuntu-integration, windows-integration]
    runs-on: ubuntu-latest

    steps:

    - name: Project checkout
      uses: actions/checkout@v3
      with:
        # Number of commits to fetch. 0 indicates all history for all branches and tags (default 1).
        fetch-depth: '0'

    - name: Get the latest tag in repo
      # result in steps.git_tag.outputs.tag
      id: git_tag
      uses: pavelsaman/git-nth-last-tag@v1

    - name: Get the release associated with the found tag
      id: latest_release
      uses: kaliber5/action-get-release@v1
      with:
        tag_name: ${{steps.git_tag.outputs.tag}}
        token: ${{ env.GITHUB_TOKEN }}
        # latest: true

    - name: Download artifacts locally
      # setting no name will download all the produced artifacts in the
      # workspace after creating a directory with their container name
      # in this case:
      # ${{github.workspace}}/${{env.ARTIFACTS}}/
      uses: actions/download-artifact@v3

    # upload asset see [Yet Another Upload Release Asset Action](https://github.com/marketplace/actions/yet-another-upload-release-asset-action)
    - name: Automatic asset upload if pre-release
      uses: shogo82148/actions-upload-release-asset@v1
      if: ${{ steps.latest_release.outputs.prerelease }}
      with:
        # upload_url: ${{ github.event.release.upload_url }}
        # upload_url: ${{ steps.latest_release.outputs.upload_url }}
        upload_url: ${{ steps.latest_release.outputs.upload_url }}
        # asset_path: ${{github.workspace}}/build/*.deb
        asset_path: ${{github.workspace}}/${{env.ARTIFACTS}}/*
