name: Linux Fedora Integration

on:
  push:
    branches: [ "trunk" ]
  workflow_dispatch:
    branches: [ "trunk" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ github.token }}
  ARTIFACTS: packages

jobs:
  fedora-integration:

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:

    - name: Project checkout
      uses: actions/checkout@v3
      with:
        # Number of commits to fetch. 0 indicates all history for all branches and tags (default 1).
        fetch-depth: '0'

    - name: Docker build & run
      working-directory: ${{github.workspace}}/docker
      run: |
        mkdir ${{github.workspace}}/build
        docker build -t odox-fedora -f Dockerfile.fedora .
        docker run -t --volume $(realpath ${{github.workspace}}):/in --volume $(realpath ${{github.workspace}})/build:/out odox-fedora

    - name: Upload produced artifacts
      uses: actions/upload-artifact@v3
      id: upload-artifacts
      with:
        name: ${{env.ARTIFACTS}}
        path: ${{github.workspace}}/build/*.rpm
